### ISSUE TITLE
Add ssh-keyscan for github.com and gitlab.com to default dockerfiles

### ISSUE THREAD

**Issue by rambo** [advian-oss/docker-pyenv-tox#10]
`mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab.com github.com | sort > ~/.ssh/known_hosts`

So working with private repos on these hosts doesn't require extra keyscans in the users dockerfiles

refs #9 #8 #7

**Comment by kahara** [comment]
Note, `sort` isn't actually necessary here.
